version: "3"
services: 
    web:
        build: 
            context: .
            dockerfile: fishingApi/Dockerfile
        ports:
            - "5000:80"
        depends_on: 
            - db
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
        env_file: ./.env
        environment: 
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: ${ACCEPT_EULA}